version: "3.9"

services: 
  web_app:
    container_name: web_app
    build: ./Docker  # path to the Dockerfile (context)
    restart: unless-stopped
    ports: 
      - 8080:5000  # port mapping (5000 = default flask development port)
    volumes:  # directory mapping
      - ./App:/App
      - ./Clothing Detection and Classification/SavedRuns/:/Clothing Detection and Classification/SavedRuns/
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]